FROM python:3

WORKDIR /usr/src/app

ENV SCHEDULE_PARSER_TELEGRAM_TOKEN = os.environ["SCHEDULER_PARSER_TELEGRAM_TOKEN"]
ENV SUPABASE_URL = os.environ["SCHEDULER_SUPABASE_URL"]
ENV SUPABASE_ANON_KEY = os.environ["SCHEDULER_SUPABASE_ANON_KEY"]
ENV REDIS_HOST_URL = os.environ["SCHEDULER_REDIS_HOST_URL"]
ENV REDIS_PORT = os.environ["SCHEDULER_REDIS_PORT"]
ENV REDIS_PASSWORD = os.environ["SCHEDULER_REDIS_PASSWORD"]
ENV REDIS_USERNAME = os.environ["SCHEDULER_REDIS_USERNAME"]

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./bot.py" ]